-d
E:\soot\sootOutput
-android-jars
C:\Users\Xiaofei\AppData\Local\Android\Sdk\platforms
-package
org.wikipedia
-process-dir
E:\apk-analysis\org.wikipedia.apk
-apktool-dir
E:\apk-analysis\org.wikipedia
-token-dir
E:\apk_sequences
-process-multiple-dex
-allow-phantom-refs